name: Terraform Lint & Validate (VCS-driven)

on:
  push:
    branches:
      - main        # runs only for pushes to main
  pull_request:
    branches:
      - main        # runs for PRs targeting main

jobs:
  lint-and-validate:
    name: Lint & Validate Terraform
    runs-on: ubuntu-latest
    concurrency:
      group: terraform-lint-validate
      cancel-in-progress: true

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.13.3

      - name: List changed files
        if: github.event_name == 'pull_request'
        run: |
          echo "Changed files in PR:"
          git --no-pager diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.sha }} || true

      - name: Terraform fmt (check)
        run: terraform fmt -check -recursive

      - name: Terraform init (for validation only)
        run: terraform init -backend=false -input=false

      - name: Terraform validate
        run: terraform validate -no-color

      - name: Check provider lockfile (optional)
        run: |
          if [ -f ".terraform.lock.hcl" ]; then
            echo "Provider lockfile present: .terraform.lock.hcl"
          else
            echo "No provider lockfile found"
          fi
